model_name: polynomial
neurons: 1, 10, 20, 10, 1
space_bounds: [-1, 1]
train_size: 10000
test_size: 1000
activation: GELU
learning_rate: 0.01
optimizer: Adam
nr_steps: 500000
batch_size: 100
eval_steps: 2000
folder_name: "trained_models/polynomial"